
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "STATE ID VARIABLE\n        state : STATE ID '{' expressions '}'\n        \n        expressions : expression\n        \n        expression : assign\n                   | empty\n        assign : VARIABLE '=' ID ';'empty : "
    
_lr_action_items = {'=':([7,],[11,]),'STATE':([0,],[1,]),';':([12,],[13,]),'VARIABLE':([4,],[7,]),'{':([3,],[4,]),'}':([4,5,6,8,9,13,],[-6,-3,10,-2,-4,-5,]),'ID':([1,11,],[3,12,]),'$end':([2,10,],[0,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'state':([0,],[2,]),'expression':([4,],[8,]),'expressions':([4,],[6,]),'empty':([4,],[9,]),'assign':([4,],[5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> state","S'",1,None,None,None),
  ('state -> STATE ID { expressions }','state',5,'p_state','bt_parser.py',31),
  ('expressions -> expression','expressions',1,'p_expressions_single','bt_parser.py',46),
  ('expression -> assign','expression',1,'p_expression','bt_parser.py',54),
  ('expression -> empty','expression',1,'p_expression','bt_parser.py',55),
  ('assign -> VARIABLE = ID ;','assign',4,'p_assign','bt_parser.py',62),
  ('empty -> <empty>','empty',0,'p_empty','bt_parser.py',68),
]
